/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as ApiPublicNowpaymentsIpnRouteImport } from './routes/api/public/nowpayments-ipn'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNowpaymentsIpnRoute = ApiPublicNowpaymentsIpnRouteImport.update({
  id: '/api/public/nowpayments-ipn',
  path: '/api/public/nowpayments-ipn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/games': typeof GamesRoute
  '/rewards': typeof RewardsRoute
  '/signin': typeof SigninRoute
  '/wallet': typeof WalletRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/api/public/nowpayments-ipn': typeof ApiPublicNowpaymentsIpnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/games': typeof GamesRoute
  '/rewards': typeof RewardsRoute
  '/signin': typeof SigninRoute
  '/wallet': typeof WalletRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/api/public/nowpayments-ipn': typeof ApiPublicNowpaymentsIpnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/games': typeof GamesRoute
  '/rewards': typeof RewardsRoute
  '/signin': typeof SigninRoute
  '/wallet': typeof WalletRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/api/public/nowpayments-ipn': typeof ApiPublicNowpaymentsIpnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/games'
    | '/rewards'
    | '/signin'
    | '/wallet'
    | '/game/$gameId'
    | '/api/public/nowpayments-ipn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/games'
    | '/rewards'
    | '/signin'
    | '/wallet'
    | '/game/$gameId'
    | '/api/public/nowpayments-ipn'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/games'
    | '/rewards'
    | '/signin'
    | '/wallet'
    | '/game/$gameId'
    | '/api/public/nowpayments-ipn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  GamesRoute: typeof GamesRoute
  RewardsRoute: typeof RewardsRoute
  SigninRoute: typeof SigninRoute
  WalletRoute: typeof WalletRoute
  GameGameIdRoute: typeof GameGameIdRoute
  ApiPublicNowpaymentsIpnRoute: typeof ApiPublicNowpaymentsIpnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nowpayments-ipn': {
      id: '/api/public/nowpayments-ipn'
      path: '/api/public/nowpayments-ipn'
      fullPath: '/api/public/nowpayments-ipn'
      preLoaderRoute: typeof ApiPublicNowpaymentsIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  GamesRoute: GamesRoute,
  RewardsRoute: RewardsRoute,
  SigninRoute: SigninRoute,
  WalletRoute: WalletRoute,
  GameGameIdRoute: GameGameIdRoute,
  ApiPublicNowpaymentsIpnRoute: ApiPublicNowpaymentsIpnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
